// Generated by CoffeeScript 1.6.3
var registry;

registry = require('npm-stats')();

module.exports = function(args) {
  var getDownloads, print;
  print = function(name, total) {
    return console.log("" + name + " has " + total + " downloads");
  };
  getDownloads = function(name, i) {
    return registry.module(name).downloads(function(err, data) {
      var arr, downloads, total, _i, _len;
      if (err) {
        throw err;
      }
      arr = [0];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        downloads = data[_i];
        arr.push(downloads.value);
      }
      total = arr.reduce(function(a, b) {
        return a + b;
      });
      return print(name, total);
    });
  };
  return registry.user(args[0]).list(function(err, data) {
    var i, name, _i, _len, _results;
    if (err) {
      throw err;
    }
    _results = [];
    for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
      name = data[i];
      _results.push(getDownloads(name, i));
    }
    return _results;
  });
};
