// Generated by CoffeeScript 1.6.3
var clearTerminal, getAllModuleDownloads, getAuthorsModules, getModuleDownloads, getTotalDownloads, printAuthorModules, printModuleStats, printModuleTotals, registry, sortModulesByDownloads, when_;

registry = require('npm-stats')();

when_ = require('when');

clearTerminal = function() {
  return process.stdout.write('\u001B[2J\u001B[0;0f');
};

printAuthorModules = function(author, count) {
  return console.log("" + author + " has published " + count + " modules:\n");
};

printModuleStats = function(module) {
  return console.log("* " + module.name + " has been download " + module.downloads + " times");
};

printModuleTotals = function(data) {
  var module, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    module = data[_i];
    _results.push(printModuleStats(module));
  }
  return _results;
};

getTotalDownloads = function(data, key) {
  var total;
  return total = Object.keys(data).reduce((function(previous, i) {
    return previous + data[i][key];
  }), 0);
};

sortModulesByDownloads = function(arr, key) {
  var sorted;
  return sorted = arr.sort(function(a, b) {
    var x, y;
    x = a[key];
    y = b[key];
    if (x > y) {
      return -1;
    } else {
      if (x < y) {
        return 1;
      } else {
        return 0;
      }
    }
  });
};

getAuthorsModules = function(author) {
  var deferred;
  deferred = when_.defer();
  registry.user(author).list(function(err, data) {
    if (err) {
      deferred.reject(new Error(err));
    }
    if (data.length === 0) {
      return deferred.reject(new Error("No NPM modules found for user " + author + "!"));
    } else {
      return deferred.resolve(data);
    }
  });
  return deferred.promise;
};

getModuleDownloads = function(module) {
  var deferred;
  deferred = when_.defer();
  registry.module(module).downloads(function(err, data) {
    var obj;
    if (err) {
      return deferred.reject(new Error(err));
    } else {
      obj = {
        name: module,
        downloads: getTotalDownloads(data, 'value')
      };
      return deferred.resolve(obj);
    }
  });
  return deferred.promise;
};

getAllModuleDownloads = function(modules) {
  var deferreds, i, len;
  deferreds = [];
  i = 0;
  len = modules.length;
  while (i < len) {
    deferreds.push(getModuleDownloads(modules[i]));
    i++;
  }
  return when_.all(deferreds);
};

module.exports = function(author) {
  clearTerminal();
  return getAuthorsModules(author).then(function(modules) {
    printAuthorModules(author, modules.length);
    return getAllModuleDownloads(modules).then(function(data) {
      return sortModulesByDownloads(data, 'downloads');
    }, function(err) {
      return console.error(err);
    });
  }, function(err) {
    return console.error(err);
  }).then(function(data) {
    return printModuleTotals(data);
  });
};
